name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/conda-forge
  - https://repo.mamba.pm/emscripten-forge
dependencies:
  - conda-forge::ipywidgets
  - conda-forge::numpy
  - conda-forge::matplotlib
  - conda-forge::seaborn
  - conda-forge::statsmodels
  - conda-forge::pandas